name: 'infracost'

on:
  pull_request:
    paths:
      - 'env/prod/**/**.tf'

jobs:
  terraform:
    name: 'infracost'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.base.ref }}

    - name: Get modified dir names
      id: changed-dir-names
      uses: tj-actions/changed-files@v39
      with:
        dir_names: "true"
        files: |
          env/**

    - name: List dirs with changes
      run: |
        for dir in ${{ steps.changed-dir-names.outputs.all_changed_files }}; do
          echo "$dir was changed"
        done

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    # Setup Infracost
    - name: Setup Infracost
      uses: infracost/actions/setup@v2
      with:
        api-key: ${{ secrets.INFRACOST_API_KEY }}

    # Generate Infracost JSON file as the baseline.
    - name: Generate Infracost cost estimate baseline
      run: |
        for dir in ${{ steps.changed-dir-names.outputs.all_changed_files }}; do
          infracost breakdown --path=$dir \
                            --format=json \
                            --out-file=/tmp/infracost-base-$dir.json
        done

    # Checkout the current PR branch so we can create a diff.
    - name: Checkout PR branch
      uses: actions/checkout@v3

    # Generate an Infracost diff and save it to a JSON file.
    - name: Generate Infracost diff
      run: |
        for dir in ${{ steps.changed-dir-names.outputs.all_changed_files }}; do
          infracost diff --path=$dir \
                        --format=json \
                        --compare-to=/tmp/infracost-base-$dir.json \
                        --out-file=/tmp/infracost-$dir.json
        done

    - name: Post Infracost comment
      run: |
        for dir in ${{ steps.changed-dir-names.outputs.all_changed_files }}; do
          infracost comment github --path=/tmp/infracost-$dir.json \
                                   --repo=$GITHUB_REPOSITORY \
                                   --github-token=${{github.token}} \
                                   --pull-request=${{github.event.pull_request.number}} \
                                   --behavior=update
        done
