name: "Terraform"
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'env/prod/**/**.tf'

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get modified dir names
        id: changed-dir-names
        uses: tj-actions/changed-files@v39
        with:
          dir_names: "true"
          files: |
            env/**

      - name: List dirs with changes
        run: |
          for dir in ${{ steps.changed-dir-names.outputs.all_changed_files }}; do
            echo "$dir was changed"
          done

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Format
        id: fmt
        run: |
          for dir in ${{ steps.changed-dir-names.outputs.all_changed_files }}; do
            cd $dir
            terraform fmt -check
            cd -
          done

      - name: Terraform Init
        id: init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: |
          for dir in ${{ steps.changed-dir-names.outputs.all_changed_files }}; do
            cd $dir
            terraform init
            cd -
          done
      
      - name: Terraform Validate
        id: validate
        run: |
          for dir in ${{ steps.changed-dir-names.outputs.all_changed_files }}; do
            cd $dir
            terraform validate -no-color
            cd -
          done

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'pull_request'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DIGITALOCEAN_TOKEN: ${{ secrets.DO_TOKEN}}
          AWS_REGION: us-east-1
        run: |
          for dir in ${{ steps.changed-dir-names.outputs.all_changed_files }}; do
            cd $dir
            terraform plan -no-color
            cd -
          done
        continue-on-error: false

      - uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          script: |
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`

            <details><summary>Show Plan</summary>

            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`

            </details>

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Terraform Plan Upload
        if: steps.plan.outcome == 'success'
        run: |
          for dir in ${{ steps.changed-dir-names.outputs.all_changed_files }}; do
            item=$(echo $dir|sed "s/\//-/g")
            cd $dir
            terraform plan -out=${{ github.workspace }}/$item.plan
          done
      - uses: actions/upload-artifact@v3
        with:
          path: ${{ github.workspace }}/*.plan

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DIGITALOCEAN_TOKEN: ${{ secrets.DO_TOKEN}}
          AWS_REGION: us-east-1
        run: |
          for dir in ${{ steps.changed-dir-names.outputs.all_changed_files }}; do
            cd $dir
            terraform apply -auto-approve
            cd -
          done
